### ISSUE TITLE
Documentation and sample to parse a lambda witn a custom parameter type.

### ISSUE THREAD

**Issue by malclear** [xaviersolau/ExpressionTools#41]
**Is your feature request related to a problem? Please describe.**
I am struggling to find the correct usage for resolving a custom parameter type. For example, if I have...
```
var expToParse = "(IFoo foo) => foo.Value + 1";
```
 and `IFoo` is a interface with a single implementation, `Foo`, I always receive the message stating ""Unknown type IFoo"). 
The `typeVisitor` only ever considers the 6 `predefinedTypeMap` elements. 
 
I'm hoping you could include an example in the documentation having this pattern. 

I have tried providing my own custom `ParameterTypeResolver`, but there's simply something I'm not understanding.

**Comment by xaviersolau** [comment]
Hello,

It looks like something is missing here... I will work on it.

Any way here is a work around:

```csharp
// Set the expression to parse
var expToParse = "x => x.Value + 1";

// We need to create the parser with a ParameterTypeResolver that will resolve the 'x' parameter as 'IFoo'.
var expressionParser = new ExpressionParser(
parameterTypeResolver: new SingleParameterTypeResolver(typeof(IFoo)));

// We can just parse the expression.
var expression = expressionParser.Parse<Func<IFoo, int>>(expToParse);
```

**Comment by xaviersolau** [comment]
I am going to add the feature to support the parameter type name resolution. The new version will allow you to parse the expression this way:

```csharp
// Set the expression to parse
var expToParse = "(IFoo x) => x.Value + 1";

// We need to create the parser with a TypeNameResolver that will resolve the parameter type.
var expressionParser = new ExpressionParser(
typeNameResolver: new BasicTypeNameResolver(typeof(IFoo)));

// We can just parse the expression.
var expression = expressionParser.Parse<Func<IFoo, int>>(expToParse);
```

Hope this will help.

**Comment by xaviersolau** [comment]
version 1.0.3 is available [here](https://www.nuget.org/packages/SoloX.ExpressionTools.Parser/).
